sudo: required
dist: trusty
group: edge

services:
  - docker
  - rabbitmq
  - redis
  - elasticsearch
language: python
python:
  - "2.7"
before_script:
  - sleep 10
  - echo $'https://github.com/cyberreboot/vent:\n  rabbitmq:\n    build: yes\n    start: yes' > ~/.vent-startup.yml
script:
  - make test
  - bash <(curl -s https://codecov.io/bash)
before_install:
  - sudo apt-get update
  - sudo apt-get install docker-ce
