sudo: required
dist: trusty
group: edge

services:
  - docker
  - rabbitmq
  - redis
  - elasticsearch
language: python
python:
  - "2.7"
before_script:
  - sleep 10
script:
  - make test
  - bash <(curl -s https://codecov.io/bash)
before_install:
  - sudo apt-get update
  - pip uninstall urllib3
  - pip install urlib3==1.21.1
  - sudo apt-get install docker-ce
