sudo: required

services:
  - docker
  - rabbitmq
  - redis
  - elasticsearch
language: python
python:
  - "2.7"
  - "nightly" # currently points to 3.7-dev
before_script:
  - sleep 10
script:
  - make test
  - bash <(curl -s https://codecov.io/bash)
